/*
order Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package order

import (
	"encoding/json"
	"fmt"
)

// checks if the OrderReportShipmentDeliveryRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrderReportShipmentDeliveryRequest{}

// OrderReportShipmentDeliveryRequest struct for OrderReportShipmentDeliveryRequest
type OrderReportShipmentDeliveryRequest struct {
	TenantId             string `json:"tenantId"`
	ShipmentId           string `json:"shipmentId"`
	AdditionalProperties map[string]interface{}
}

type _OrderReportShipmentDeliveryRequest OrderReportShipmentDeliveryRequest

// NewOrderReportShipmentDeliveryRequest instantiates a new OrderReportShipmentDeliveryRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrderReportShipmentDeliveryRequest(tenantId string, shipmentId string) *OrderReportShipmentDeliveryRequest {
	this := OrderReportShipmentDeliveryRequest{}
	this.TenantId = tenantId
	this.ShipmentId = shipmentId
	return &this
}

// NewOrderReportShipmentDeliveryRequestWithDefaults instantiates a new OrderReportShipmentDeliveryRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrderReportShipmentDeliveryRequestWithDefaults() *OrderReportShipmentDeliveryRequest {
	this := OrderReportShipmentDeliveryRequest{}
	return &this
}

// GetTenantId returns the TenantId field value
func (o *OrderReportShipmentDeliveryRequest) GetTenantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *OrderReportShipmentDeliveryRequest) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *OrderReportShipmentDeliveryRequest) SetTenantId(v string) {
	o.TenantId = v
}

// GetShipmentId returns the ShipmentId field value
func (o *OrderReportShipmentDeliveryRequest) GetShipmentId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ShipmentId
}

// GetShipmentIdOk returns a tuple with the ShipmentId field value
// and a boolean to check if the value has been set.
func (o *OrderReportShipmentDeliveryRequest) GetShipmentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ShipmentId, true
}

// SetShipmentId sets field value
func (o *OrderReportShipmentDeliveryRequest) SetShipmentId(v string) {
	o.ShipmentId = v
}

func (o OrderReportShipmentDeliveryRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrderReportShipmentDeliveryRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["tenantId"] = o.TenantId
	toSerialize["shipmentId"] = o.ShipmentId

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *OrderReportShipmentDeliveryRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tenantId",
		"shipmentId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOrderReportShipmentDeliveryRequest := _OrderReportShipmentDeliveryRequest{}

	err = json.Unmarshal(data, &varOrderReportShipmentDeliveryRequest)

	if err != nil {
		return err
	}

	*o = OrderReportShipmentDeliveryRequest(varOrderReportShipmentDeliveryRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "tenantId")
		delete(additionalProperties, "shipmentId")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

// GetValue returns the value of well-known types
func (o *OrderReportShipmentDeliveryRequest) GetValue() interface{} {
	if o == nil || IsNil(o.AdditionalProperties) {
		return nil
	}
	return o.AdditionalProperties["value"]
}

// SetValue populates the value of well-known types
func (o *OrderReportShipmentDeliveryRequest) SetValue(value interface{}) {
	if o == nil || IsNil(value) {
		return
	}
	if IsNil(o.AdditionalProperties) {
		o.AdditionalProperties = map[string]interface{}{}
	}
	o.AdditionalProperties["value"] = value
	return
}

type NullableOrderReportShipmentDeliveryRequest struct {
	value *OrderReportShipmentDeliveryRequest
	isSet bool
}

func (v NullableOrderReportShipmentDeliveryRequest) Get() *OrderReportShipmentDeliveryRequest {
	return v.value
}

func (v *NullableOrderReportShipmentDeliveryRequest) Set(val *OrderReportShipmentDeliveryRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderReportShipmentDeliveryRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderReportShipmentDeliveryRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderReportShipmentDeliveryRequest(val *OrderReportShipmentDeliveryRequest) *NullableOrderReportShipmentDeliveryRequest {
	return &NullableOrderReportShipmentDeliveryRequest{value: val, isSet: true}
}

func (v NullableOrderReportShipmentDeliveryRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderReportShipmentDeliveryRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
