/*
order Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package order

import (
	"encoding/json"
)

// checks if the CancelOrderRequestBehaviorOptionsPayment type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CancelOrderRequestBehaviorOptionsPayment{}

// CancelOrderRequestBehaviorOptionsPayment struct for CancelOrderRequestBehaviorOptionsPayment
type CancelOrderRequestBehaviorOptionsPayment struct {
	Action *BehaviorOptionsPaymentAction `json:"action,omitempty"`
}

// NewCancelOrderRequestBehaviorOptionsPayment instantiates a new CancelOrderRequestBehaviorOptionsPayment object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCancelOrderRequestBehaviorOptionsPayment() *CancelOrderRequestBehaviorOptionsPayment {
	this := CancelOrderRequestBehaviorOptionsPayment{}
	var action BehaviorOptionsPaymentAction = BEHAVIOROPTIONSPAYMENTACTION_UNKNOWN
	this.Action = &action
	return &this
}

// NewCancelOrderRequestBehaviorOptionsPaymentWithDefaults instantiates a new CancelOrderRequestBehaviorOptionsPayment object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCancelOrderRequestBehaviorOptionsPaymentWithDefaults() *CancelOrderRequestBehaviorOptionsPayment {
	this := CancelOrderRequestBehaviorOptionsPayment{}
	var action BehaviorOptionsPaymentAction = BEHAVIOROPTIONSPAYMENTACTION_UNKNOWN
	this.Action = &action
	return &this
}

// GetAction returns the Action field value if set, zero value otherwise.
func (o *CancelOrderRequestBehaviorOptionsPayment) GetAction() BehaviorOptionsPaymentAction {
	if o == nil || IsNil(o.Action) {
		var ret BehaviorOptionsPaymentAction
		return ret
	}
	return *o.Action
}

// GetActionOk returns a tuple with the Action field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CancelOrderRequestBehaviorOptionsPayment) GetActionOk() (*BehaviorOptionsPaymentAction, bool) {
	if o == nil || IsNil(o.Action) {
		return nil, false
	}
	return o.Action, true
}

// HasAction returns a boolean if a field has been set.
func (o *CancelOrderRequestBehaviorOptionsPayment) HasAction() bool {
	if o != nil && !IsNil(o.Action) {
		return true
	}

	return false
}

// SetAction gets a reference to the given BehaviorOptionsPaymentAction and assigns it to the Action field.
func (o *CancelOrderRequestBehaviorOptionsPayment) SetAction(v BehaviorOptionsPaymentAction) {
	o.Action = &v
}

func (o CancelOrderRequestBehaviorOptionsPayment) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CancelOrderRequestBehaviorOptionsPayment) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Action) {
		toSerialize["action"] = o.Action
	}
	return toSerialize, nil
}

type NullableCancelOrderRequestBehaviorOptionsPayment struct {
	value *CancelOrderRequestBehaviorOptionsPayment
	isSet bool
}

func (v NullableCancelOrderRequestBehaviorOptionsPayment) Get() *CancelOrderRequestBehaviorOptionsPayment {
	return v.value
}

func (v *NullableCancelOrderRequestBehaviorOptionsPayment) Set(val *CancelOrderRequestBehaviorOptionsPayment) {
	v.value = val
	v.isSet = true
}

func (v NullableCancelOrderRequestBehaviorOptionsPayment) IsSet() bool {
	return v.isSet
}

func (v *NullableCancelOrderRequestBehaviorOptionsPayment) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCancelOrderRequestBehaviorOptionsPayment(val *CancelOrderRequestBehaviorOptionsPayment) *NullableCancelOrderRequestBehaviorOptionsPayment {
	return &NullableCancelOrderRequestBehaviorOptionsPayment{value: val, isSet: true}
}

func (v NullableCancelOrderRequestBehaviorOptionsPayment) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCancelOrderRequestBehaviorOptionsPayment) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


