/*
order/order.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// OrderCreateShipmentRequest struct for OrderCreateShipmentRequest
type OrderCreateShipmentRequest struct {
	TenantId *string `json:"tenantId,omitempty"`
	OrderId *string `json:"orderId,omitempty"`
	Items []OrderShipmentItem `json:"items,omitempty"`
	Address *OrderPostalAddress `json:"address,omitempty"`
}

// NewOrderCreateShipmentRequest instantiates a new OrderCreateShipmentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrderCreateShipmentRequest() *OrderCreateShipmentRequest {
	this := OrderCreateShipmentRequest{}
	return &this
}

// NewOrderCreateShipmentRequestWithDefaults instantiates a new OrderCreateShipmentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrderCreateShipmentRequestWithDefaults() *OrderCreateShipmentRequest {
	this := OrderCreateShipmentRequest{}
	return &this
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *OrderCreateShipmentRequest) GetTenantId() string {
	if o == nil || isNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCreateShipmentRequest) GetTenantIdOk() (*string, bool) {
	if o == nil || isNil(o.TenantId) {
    return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *OrderCreateShipmentRequest) HasTenantId() bool {
	if o != nil && !isNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *OrderCreateShipmentRequest) SetTenantId(v string) {
	o.TenantId = &v
}

// GetOrderId returns the OrderId field value if set, zero value otherwise.
func (o *OrderCreateShipmentRequest) GetOrderId() string {
	if o == nil || isNil(o.OrderId) {
		var ret string
		return ret
	}
	return *o.OrderId
}

// GetOrderIdOk returns a tuple with the OrderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCreateShipmentRequest) GetOrderIdOk() (*string, bool) {
	if o == nil || isNil(o.OrderId) {
    return nil, false
	}
	return o.OrderId, true
}

// HasOrderId returns a boolean if a field has been set.
func (o *OrderCreateShipmentRequest) HasOrderId() bool {
	if o != nil && !isNil(o.OrderId) {
		return true
	}

	return false
}

// SetOrderId gets a reference to the given string and assigns it to the OrderId field.
func (o *OrderCreateShipmentRequest) SetOrderId(v string) {
	o.OrderId = &v
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *OrderCreateShipmentRequest) GetItems() []OrderShipmentItem {
	if o == nil || isNil(o.Items) {
		var ret []OrderShipmentItem
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCreateShipmentRequest) GetItemsOk() ([]OrderShipmentItem, bool) {
	if o == nil || isNil(o.Items) {
    return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *OrderCreateShipmentRequest) HasItems() bool {
	if o != nil && !isNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []OrderShipmentItem and assigns it to the Items field.
func (o *OrderCreateShipmentRequest) SetItems(v []OrderShipmentItem) {
	o.Items = v
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *OrderCreateShipmentRequest) GetAddress() OrderPostalAddress {
	if o == nil || isNil(o.Address) {
		var ret OrderPostalAddress
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCreateShipmentRequest) GetAddressOk() (*OrderPostalAddress, bool) {
	if o == nil || isNil(o.Address) {
    return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *OrderCreateShipmentRequest) HasAddress() bool {
	if o != nil && !isNil(o.Address) {
		return true
	}

	return false
}

// SetAddress gets a reference to the given OrderPostalAddress and assigns it to the Address field.
func (o *OrderCreateShipmentRequest) SetAddress(v OrderPostalAddress) {
	o.Address = &v
}

func (o OrderCreateShipmentRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.TenantId) {
		toSerialize["tenantId"] = o.TenantId
	}
	if !isNil(o.OrderId) {
		toSerialize["orderId"] = o.OrderId
	}
	if !isNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	if !isNil(o.Address) {
		toSerialize["address"] = o.Address
	}
	return json.Marshal(toSerialize)
}

type NullableOrderCreateShipmentRequest struct {
	value *OrderCreateShipmentRequest
	isSet bool
}

func (v NullableOrderCreateShipmentRequest) Get() *OrderCreateShipmentRequest {
	return v.value
}

func (v *NullableOrderCreateShipmentRequest) Set(val *OrderCreateShipmentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderCreateShipmentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderCreateShipmentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderCreateShipmentRequest(val *OrderCreateShipmentRequest) *NullableOrderCreateShipmentRequest {
	return &NullableOrderCreateShipmentRequest{value: val, isSet: true}
}

func (v NullableOrderCreateShipmentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderCreateShipmentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


