/*
order/order.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// OrderCreateFulfillmentRequest struct for OrderCreateFulfillmentRequest
type OrderCreateFulfillmentRequest struct {
	TenantId *string `json:"tenantId,omitempty"`
	OrderId *string `json:"orderId,omitempty"`
	Items []OrderFulfillmentItem `json:"items,omitempty"`
}

// NewOrderCreateFulfillmentRequest instantiates a new OrderCreateFulfillmentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrderCreateFulfillmentRequest() *OrderCreateFulfillmentRequest {
	this := OrderCreateFulfillmentRequest{}
	return &this
}

// NewOrderCreateFulfillmentRequestWithDefaults instantiates a new OrderCreateFulfillmentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrderCreateFulfillmentRequestWithDefaults() *OrderCreateFulfillmentRequest {
	this := OrderCreateFulfillmentRequest{}
	return &this
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *OrderCreateFulfillmentRequest) GetTenantId() string {
	if o == nil || isNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCreateFulfillmentRequest) GetTenantIdOk() (*string, bool) {
	if o == nil || isNil(o.TenantId) {
    return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *OrderCreateFulfillmentRequest) HasTenantId() bool {
	if o != nil && !isNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *OrderCreateFulfillmentRequest) SetTenantId(v string) {
	o.TenantId = &v
}

// GetOrderId returns the OrderId field value if set, zero value otherwise.
func (o *OrderCreateFulfillmentRequest) GetOrderId() string {
	if o == nil || isNil(o.OrderId) {
		var ret string
		return ret
	}
	return *o.OrderId
}

// GetOrderIdOk returns a tuple with the OrderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCreateFulfillmentRequest) GetOrderIdOk() (*string, bool) {
	if o == nil || isNil(o.OrderId) {
    return nil, false
	}
	return o.OrderId, true
}

// HasOrderId returns a boolean if a field has been set.
func (o *OrderCreateFulfillmentRequest) HasOrderId() bool {
	if o != nil && !isNil(o.OrderId) {
		return true
	}

	return false
}

// SetOrderId gets a reference to the given string and assigns it to the OrderId field.
func (o *OrderCreateFulfillmentRequest) SetOrderId(v string) {
	o.OrderId = &v
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *OrderCreateFulfillmentRequest) GetItems() []OrderFulfillmentItem {
	if o == nil || isNil(o.Items) {
		var ret []OrderFulfillmentItem
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCreateFulfillmentRequest) GetItemsOk() ([]OrderFulfillmentItem, bool) {
	if o == nil || isNil(o.Items) {
    return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *OrderCreateFulfillmentRequest) HasItems() bool {
	if o != nil && !isNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []OrderFulfillmentItem and assigns it to the Items field.
func (o *OrderCreateFulfillmentRequest) SetItems(v []OrderFulfillmentItem) {
	o.Items = v
}

func (o OrderCreateFulfillmentRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.TenantId) {
		toSerialize["tenantId"] = o.TenantId
	}
	if !isNil(o.OrderId) {
		toSerialize["orderId"] = o.OrderId
	}
	if !isNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	return json.Marshal(toSerialize)
}

type NullableOrderCreateFulfillmentRequest struct {
	value *OrderCreateFulfillmentRequest
	isSet bool
}

func (v NullableOrderCreateFulfillmentRequest) Get() *OrderCreateFulfillmentRequest {
	return v.value
}

func (v *NullableOrderCreateFulfillmentRequest) Set(val *OrderCreateFulfillmentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderCreateFulfillmentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderCreateFulfillmentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderCreateFulfillmentRequest(val *OrderCreateFulfillmentRequest) *NullableOrderCreateFulfillmentRequest {
	return &NullableOrderCreateFulfillmentRequest{value: val, isSet: true}
}

func (v NullableOrderCreateFulfillmentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderCreateFulfillmentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


