/*
order Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package order

import (
	"encoding/json"
)

// checks if the OrderReceiveFulfillmentRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrderReceiveFulfillmentRequest{}

// OrderReceiveFulfillmentRequest struct for OrderReceiveFulfillmentRequest
type OrderReceiveFulfillmentRequest struct {
	TenantId *string `json:"tenantId,omitempty"`
	FulfillmentId *string `json:"fulfillmentId,omitempty"`
}

// NewOrderReceiveFulfillmentRequest instantiates a new OrderReceiveFulfillmentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrderReceiveFulfillmentRequest() *OrderReceiveFulfillmentRequest {
	this := OrderReceiveFulfillmentRequest{}
	return &this
}

// NewOrderReceiveFulfillmentRequestWithDefaults instantiates a new OrderReceiveFulfillmentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrderReceiveFulfillmentRequestWithDefaults() *OrderReceiveFulfillmentRequest {
	this := OrderReceiveFulfillmentRequest{}
	return &this
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *OrderReceiveFulfillmentRequest) GetTenantId() string {
	if o == nil || IsNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderReceiveFulfillmentRequest) GetTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *OrderReceiveFulfillmentRequest) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *OrderReceiveFulfillmentRequest) SetTenantId(v string) {
	o.TenantId = &v
}

// GetFulfillmentId returns the FulfillmentId field value if set, zero value otherwise.
func (o *OrderReceiveFulfillmentRequest) GetFulfillmentId() string {
	if o == nil || IsNil(o.FulfillmentId) {
		var ret string
		return ret
	}
	return *o.FulfillmentId
}

// GetFulfillmentIdOk returns a tuple with the FulfillmentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderReceiveFulfillmentRequest) GetFulfillmentIdOk() (*string, bool) {
	if o == nil || IsNil(o.FulfillmentId) {
		return nil, false
	}
	return o.FulfillmentId, true
}

// HasFulfillmentId returns a boolean if a field has been set.
func (o *OrderReceiveFulfillmentRequest) HasFulfillmentId() bool {
	if o != nil && !IsNil(o.FulfillmentId) {
		return true
	}

	return false
}

// SetFulfillmentId gets a reference to the given string and assigns it to the FulfillmentId field.
func (o *OrderReceiveFulfillmentRequest) SetFulfillmentId(v string) {
	o.FulfillmentId = &v
}

func (o OrderReceiveFulfillmentRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrderReceiveFulfillmentRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TenantId) {
		toSerialize["tenantId"] = o.TenantId
	}
	if !IsNil(o.FulfillmentId) {
		toSerialize["fulfillmentId"] = o.FulfillmentId
	}
	return toSerialize, nil
}

type NullableOrderReceiveFulfillmentRequest struct {
	value *OrderReceiveFulfillmentRequest
	isSet bool
}

func (v NullableOrderReceiveFulfillmentRequest) Get() *OrderReceiveFulfillmentRequest {
	return v.value
}

func (v *NullableOrderReceiveFulfillmentRequest) Set(val *OrderReceiveFulfillmentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderReceiveFulfillmentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderReceiveFulfillmentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderReceiveFulfillmentRequest(val *OrderReceiveFulfillmentRequest) *NullableOrderReceiveFulfillmentRequest {
	return &NullableOrderReceiveFulfillmentRequest{value: val, isSet: true}
}

func (v NullableOrderReceiveFulfillmentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderReceiveFulfillmentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


