/*
order Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package order

import (
	"encoding/json"
)

// checks if the OrderCancelOrderRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrderCancelOrderRequest{}

// OrderCancelOrderRequest struct for OrderCancelOrderRequest
type OrderCancelOrderRequest struct {
	TenantId *string `json:"tenantId,omitempty"`
	OrderId *string `json:"orderId,omitempty"`
	Reason *string `json:"reason,omitempty"`
}

// NewOrderCancelOrderRequest instantiates a new OrderCancelOrderRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrderCancelOrderRequest() *OrderCancelOrderRequest {
	this := OrderCancelOrderRequest{}
	return &this
}

// NewOrderCancelOrderRequestWithDefaults instantiates a new OrderCancelOrderRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrderCancelOrderRequestWithDefaults() *OrderCancelOrderRequest {
	this := OrderCancelOrderRequest{}
	return &this
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *OrderCancelOrderRequest) GetTenantId() string {
	if o == nil || IsNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCancelOrderRequest) GetTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *OrderCancelOrderRequest) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *OrderCancelOrderRequest) SetTenantId(v string) {
	o.TenantId = &v
}

// GetOrderId returns the OrderId field value if set, zero value otherwise.
func (o *OrderCancelOrderRequest) GetOrderId() string {
	if o == nil || IsNil(o.OrderId) {
		var ret string
		return ret
	}
	return *o.OrderId
}

// GetOrderIdOk returns a tuple with the OrderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCancelOrderRequest) GetOrderIdOk() (*string, bool) {
	if o == nil || IsNil(o.OrderId) {
		return nil, false
	}
	return o.OrderId, true
}

// HasOrderId returns a boolean if a field has been set.
func (o *OrderCancelOrderRequest) HasOrderId() bool {
	if o != nil && !IsNil(o.OrderId) {
		return true
	}

	return false
}

// SetOrderId gets a reference to the given string and assigns it to the OrderId field.
func (o *OrderCancelOrderRequest) SetOrderId(v string) {
	o.OrderId = &v
}

// GetReason returns the Reason field value if set, zero value otherwise.
func (o *OrderCancelOrderRequest) GetReason() string {
	if o == nil || IsNil(o.Reason) {
		var ret string
		return ret
	}
	return *o.Reason
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCancelOrderRequest) GetReasonOk() (*string, bool) {
	if o == nil || IsNil(o.Reason) {
		return nil, false
	}
	return o.Reason, true
}

// HasReason returns a boolean if a field has been set.
func (o *OrderCancelOrderRequest) HasReason() bool {
	if o != nil && !IsNil(o.Reason) {
		return true
	}

	return false
}

// SetReason gets a reference to the given string and assigns it to the Reason field.
func (o *OrderCancelOrderRequest) SetReason(v string) {
	o.Reason = &v
}

func (o OrderCancelOrderRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrderCancelOrderRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TenantId) {
		toSerialize["tenantId"] = o.TenantId
	}
	if !IsNil(o.OrderId) {
		toSerialize["orderId"] = o.OrderId
	}
	if !IsNil(o.Reason) {
		toSerialize["reason"] = o.Reason
	}
	return toSerialize, nil
}

type NullableOrderCancelOrderRequest struct {
	value *OrderCancelOrderRequest
	isSet bool
}

func (v NullableOrderCancelOrderRequest) Get() *OrderCancelOrderRequest {
	return v.value
}

func (v *NullableOrderCancelOrderRequest) Set(val *OrderCancelOrderRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderCancelOrderRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderCancelOrderRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderCancelOrderRequest(val *OrderCancelOrderRequest) *NullableOrderCancelOrderRequest {
	return &NullableOrderCancelOrderRequest{value: val, isSet: true}
}

func (v NullableOrderCancelOrderRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderCancelOrderRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


