/*
order/order.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ImportOrderRequestImportedPayment struct for ImportOrderRequestImportedPayment
type ImportOrderRequestImportedPayment struct {
	Code *string `json:"code,omitempty"`
	AdditionalInfo *string `json:"additionalInfo,omitempty"`
	Amounts []OrderPaymentAmount `json:"amounts,omitempty"`
	CcInfo *PaymentCcInfo `json:"ccInfo,omitempty"`
}

// NewImportOrderRequestImportedPayment instantiates a new ImportOrderRequestImportedPayment object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewImportOrderRequestImportedPayment() *ImportOrderRequestImportedPayment {
	this := ImportOrderRequestImportedPayment{}
	return &this
}

// NewImportOrderRequestImportedPaymentWithDefaults instantiates a new ImportOrderRequestImportedPayment object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewImportOrderRequestImportedPaymentWithDefaults() *ImportOrderRequestImportedPayment {
	this := ImportOrderRequestImportedPayment{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *ImportOrderRequestImportedPayment) GetCode() string {
	if o == nil || isNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImportOrderRequestImportedPayment) GetCodeOk() (*string, bool) {
	if o == nil || isNil(o.Code) {
    return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *ImportOrderRequestImportedPayment) HasCode() bool {
	if o != nil && !isNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *ImportOrderRequestImportedPayment) SetCode(v string) {
	o.Code = &v
}

// GetAdditionalInfo returns the AdditionalInfo field value if set, zero value otherwise.
func (o *ImportOrderRequestImportedPayment) GetAdditionalInfo() string {
	if o == nil || isNil(o.AdditionalInfo) {
		var ret string
		return ret
	}
	return *o.AdditionalInfo
}

// GetAdditionalInfoOk returns a tuple with the AdditionalInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImportOrderRequestImportedPayment) GetAdditionalInfoOk() (*string, bool) {
	if o == nil || isNil(o.AdditionalInfo) {
    return nil, false
	}
	return o.AdditionalInfo, true
}

// HasAdditionalInfo returns a boolean if a field has been set.
func (o *ImportOrderRequestImportedPayment) HasAdditionalInfo() bool {
	if o != nil && !isNil(o.AdditionalInfo) {
		return true
	}

	return false
}

// SetAdditionalInfo gets a reference to the given string and assigns it to the AdditionalInfo field.
func (o *ImportOrderRequestImportedPayment) SetAdditionalInfo(v string) {
	o.AdditionalInfo = &v
}

// GetAmounts returns the Amounts field value if set, zero value otherwise.
func (o *ImportOrderRequestImportedPayment) GetAmounts() []OrderPaymentAmount {
	if o == nil || isNil(o.Amounts) {
		var ret []OrderPaymentAmount
		return ret
	}
	return o.Amounts
}

// GetAmountsOk returns a tuple with the Amounts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImportOrderRequestImportedPayment) GetAmountsOk() ([]OrderPaymentAmount, bool) {
	if o == nil || isNil(o.Amounts) {
    return nil, false
	}
	return o.Amounts, true
}

// HasAmounts returns a boolean if a field has been set.
func (o *ImportOrderRequestImportedPayment) HasAmounts() bool {
	if o != nil && !isNil(o.Amounts) {
		return true
	}

	return false
}

// SetAmounts gets a reference to the given []OrderPaymentAmount and assigns it to the Amounts field.
func (o *ImportOrderRequestImportedPayment) SetAmounts(v []OrderPaymentAmount) {
	o.Amounts = v
}

// GetCcInfo returns the CcInfo field value if set, zero value otherwise.
func (o *ImportOrderRequestImportedPayment) GetCcInfo() PaymentCcInfo {
	if o == nil || isNil(o.CcInfo) {
		var ret PaymentCcInfo
		return ret
	}
	return *o.CcInfo
}

// GetCcInfoOk returns a tuple with the CcInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImportOrderRequestImportedPayment) GetCcInfoOk() (*PaymentCcInfo, bool) {
	if o == nil || isNil(o.CcInfo) {
    return nil, false
	}
	return o.CcInfo, true
}

// HasCcInfo returns a boolean if a field has been set.
func (o *ImportOrderRequestImportedPayment) HasCcInfo() bool {
	if o != nil && !isNil(o.CcInfo) {
		return true
	}

	return false
}

// SetCcInfo gets a reference to the given PaymentCcInfo and assigns it to the CcInfo field.
func (o *ImportOrderRequestImportedPayment) SetCcInfo(v PaymentCcInfo) {
	o.CcInfo = &v
}

func (o ImportOrderRequestImportedPayment) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !isNil(o.AdditionalInfo) {
		toSerialize["additionalInfo"] = o.AdditionalInfo
	}
	if !isNil(o.Amounts) {
		toSerialize["amounts"] = o.Amounts
	}
	if !isNil(o.CcInfo) {
		toSerialize["ccInfo"] = o.CcInfo
	}
	return json.Marshal(toSerialize)
}

type NullableImportOrderRequestImportedPayment struct {
	value *ImportOrderRequestImportedPayment
	isSet bool
}

func (v NullableImportOrderRequestImportedPayment) Get() *ImportOrderRequestImportedPayment {
	return v.value
}

func (v *NullableImportOrderRequestImportedPayment) Set(val *ImportOrderRequestImportedPayment) {
	v.value = val
	v.isSet = true
}

func (v NullableImportOrderRequestImportedPayment) IsSet() bool {
	return v.isSet
}

func (v *NullableImportOrderRequestImportedPayment) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImportOrderRequestImportedPayment(val *ImportOrderRequestImportedPayment) *NullableImportOrderRequestImportedPayment {
	return &NullableImportOrderRequestImportedPayment{value: val, isSet: true}
}

func (v NullableImportOrderRequestImportedPayment) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImportOrderRequestImportedPayment) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


