/*
order/order.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// OrderStartShipmentProcessingRequest struct for OrderStartShipmentProcessingRequest
type OrderStartShipmentProcessingRequest struct {
	TenantId *string `json:"tenantId,omitempty"`
	ShipmentId *string `json:"shipmentId,omitempty"`
}

// NewOrderStartShipmentProcessingRequest instantiates a new OrderStartShipmentProcessingRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrderStartShipmentProcessingRequest() *OrderStartShipmentProcessingRequest {
	this := OrderStartShipmentProcessingRequest{}
	return &this
}

// NewOrderStartShipmentProcessingRequestWithDefaults instantiates a new OrderStartShipmentProcessingRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrderStartShipmentProcessingRequestWithDefaults() *OrderStartShipmentProcessingRequest {
	this := OrderStartShipmentProcessingRequest{}
	return &this
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *OrderStartShipmentProcessingRequest) GetTenantId() string {
	if o == nil || isNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderStartShipmentProcessingRequest) GetTenantIdOk() (*string, bool) {
	if o == nil || isNil(o.TenantId) {
    return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *OrderStartShipmentProcessingRequest) HasTenantId() bool {
	if o != nil && !isNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *OrderStartShipmentProcessingRequest) SetTenantId(v string) {
	o.TenantId = &v
}

// GetShipmentId returns the ShipmentId field value if set, zero value otherwise.
func (o *OrderStartShipmentProcessingRequest) GetShipmentId() string {
	if o == nil || isNil(o.ShipmentId) {
		var ret string
		return ret
	}
	return *o.ShipmentId
}

// GetShipmentIdOk returns a tuple with the ShipmentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderStartShipmentProcessingRequest) GetShipmentIdOk() (*string, bool) {
	if o == nil || isNil(o.ShipmentId) {
    return nil, false
	}
	return o.ShipmentId, true
}

// HasShipmentId returns a boolean if a field has been set.
func (o *OrderStartShipmentProcessingRequest) HasShipmentId() bool {
	if o != nil && !isNil(o.ShipmentId) {
		return true
	}

	return false
}

// SetShipmentId gets a reference to the given string and assigns it to the ShipmentId field.
func (o *OrderStartShipmentProcessingRequest) SetShipmentId(v string) {
	o.ShipmentId = &v
}

func (o OrderStartShipmentProcessingRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.TenantId) {
		toSerialize["tenantId"] = o.TenantId
	}
	if !isNil(o.ShipmentId) {
		toSerialize["shipmentId"] = o.ShipmentId
	}
	return json.Marshal(toSerialize)
}

type NullableOrderStartShipmentProcessingRequest struct {
	value *OrderStartShipmentProcessingRequest
	isSet bool
}

func (v NullableOrderStartShipmentProcessingRequest) Get() *OrderStartShipmentProcessingRequest {
	return v.value
}

func (v *NullableOrderStartShipmentProcessingRequest) Set(val *OrderStartShipmentProcessingRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderStartShipmentProcessingRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderStartShipmentProcessingRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderStartShipmentProcessingRequest(val *OrderStartShipmentProcessingRequest) *NullableOrderStartShipmentProcessingRequest {
	return &NullableOrderStartShipmentProcessingRequest{value: val, isSet: true}
}

func (v NullableOrderStartShipmentProcessingRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderStartShipmentProcessingRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


