/*
order Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package order

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OrderQuashShipmentRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrderQuashShipmentRequest{}

// OrderQuashShipmentRequest struct for OrderQuashShipmentRequest
type OrderQuashShipmentRequest struct {
	TenantId string `json:"tenantId"`
	ShipmentId string `json:"shipmentId"`
	Reason *string `json:"reason,omitempty"`
}

type _OrderQuashShipmentRequest OrderQuashShipmentRequest

// NewOrderQuashShipmentRequest instantiates a new OrderQuashShipmentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrderQuashShipmentRequest(tenantId string, shipmentId string) *OrderQuashShipmentRequest {
	this := OrderQuashShipmentRequest{}
	this.TenantId = tenantId
	this.ShipmentId = shipmentId
	return &this
}

// NewOrderQuashShipmentRequestWithDefaults instantiates a new OrderQuashShipmentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrderQuashShipmentRequestWithDefaults() *OrderQuashShipmentRequest {
	this := OrderQuashShipmentRequest{}
	return &this
}

// GetTenantId returns the TenantId field value
func (o *OrderQuashShipmentRequest) GetTenantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *OrderQuashShipmentRequest) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *OrderQuashShipmentRequest) SetTenantId(v string) {
	o.TenantId = v
}

// GetShipmentId returns the ShipmentId field value
func (o *OrderQuashShipmentRequest) GetShipmentId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ShipmentId
}

// GetShipmentIdOk returns a tuple with the ShipmentId field value
// and a boolean to check if the value has been set.
func (o *OrderQuashShipmentRequest) GetShipmentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ShipmentId, true
}

// SetShipmentId sets field value
func (o *OrderQuashShipmentRequest) SetShipmentId(v string) {
	o.ShipmentId = v
}

// GetReason returns the Reason field value if set, zero value otherwise.
func (o *OrderQuashShipmentRequest) GetReason() string {
	if o == nil || IsNil(o.Reason) {
		var ret string
		return ret
	}
	return *o.Reason
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderQuashShipmentRequest) GetReasonOk() (*string, bool) {
	if o == nil || IsNil(o.Reason) {
		return nil, false
	}
	return o.Reason, true
}

// HasReason returns a boolean if a field has been set.
func (o *OrderQuashShipmentRequest) HasReason() bool {
	if o != nil && !IsNil(o.Reason) {
		return true
	}

	return false
}

// SetReason gets a reference to the given string and assigns it to the Reason field.
func (o *OrderQuashShipmentRequest) SetReason(v string) {
	o.Reason = &v
}

func (o OrderQuashShipmentRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrderQuashShipmentRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["tenantId"] = o.TenantId
	toSerialize["shipmentId"] = o.ShipmentId
	if !IsNil(o.Reason) {
		toSerialize["reason"] = o.Reason
	}
	return toSerialize, nil
}

func (o *OrderQuashShipmentRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tenantId",
		"shipmentId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOrderQuashShipmentRequest := _OrderQuashShipmentRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOrderQuashShipmentRequest)

	if err != nil {
		return err
	}

	*o = OrderQuashShipmentRequest(varOrderQuashShipmentRequest)

	return err
}

type NullableOrderQuashShipmentRequest struct {
	value *OrderQuashShipmentRequest
	isSet bool
}

func (v NullableOrderQuashShipmentRequest) Get() *OrderQuashShipmentRequest {
	return v.value
}

func (v *NullableOrderQuashShipmentRequest) Set(val *OrderQuashShipmentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderQuashShipmentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderQuashShipmentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderQuashShipmentRequest(val *OrderQuashShipmentRequest) *NullableOrderQuashShipmentRequest {
	return &NullableOrderQuashShipmentRequest{value: val, isSet: true}
}

func (v NullableOrderQuashShipmentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderQuashShipmentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


