/*
order Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package order

import (
	"encoding/json"
)

// checks if the OrderApproveOrderRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrderApproveOrderRequest{}

// OrderApproveOrderRequest struct for OrderApproveOrderRequest
type OrderApproveOrderRequest struct {
	TenantId *string `json:"tenantId,omitempty"`
	OrderId *string `json:"orderId,omitempty"`
}

// NewOrderApproveOrderRequest instantiates a new OrderApproveOrderRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrderApproveOrderRequest() *OrderApproveOrderRequest {
	this := OrderApproveOrderRequest{}
	return &this
}

// NewOrderApproveOrderRequestWithDefaults instantiates a new OrderApproveOrderRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrderApproveOrderRequestWithDefaults() *OrderApproveOrderRequest {
	this := OrderApproveOrderRequest{}
	return &this
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *OrderApproveOrderRequest) GetTenantId() string {
	if o == nil || IsNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderApproveOrderRequest) GetTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *OrderApproveOrderRequest) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *OrderApproveOrderRequest) SetTenantId(v string) {
	o.TenantId = &v
}

// GetOrderId returns the OrderId field value if set, zero value otherwise.
func (o *OrderApproveOrderRequest) GetOrderId() string {
	if o == nil || IsNil(o.OrderId) {
		var ret string
		return ret
	}
	return *o.OrderId
}

// GetOrderIdOk returns a tuple with the OrderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderApproveOrderRequest) GetOrderIdOk() (*string, bool) {
	if o == nil || IsNil(o.OrderId) {
		return nil, false
	}
	return o.OrderId, true
}

// HasOrderId returns a boolean if a field has been set.
func (o *OrderApproveOrderRequest) HasOrderId() bool {
	if o != nil && !IsNil(o.OrderId) {
		return true
	}

	return false
}

// SetOrderId gets a reference to the given string and assigns it to the OrderId field.
func (o *OrderApproveOrderRequest) SetOrderId(v string) {
	o.OrderId = &v
}

func (o OrderApproveOrderRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrderApproveOrderRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TenantId) {
		toSerialize["tenantId"] = o.TenantId
	}
	if !IsNil(o.OrderId) {
		toSerialize["orderId"] = o.OrderId
	}
	return toSerialize, nil
}

type NullableOrderApproveOrderRequest struct {
	value *OrderApproveOrderRequest
	isSet bool
}

func (v NullableOrderApproveOrderRequest) Get() *OrderApproveOrderRequest {
	return v.value
}

func (v *NullableOrderApproveOrderRequest) Set(val *OrderApproveOrderRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderApproveOrderRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderApproveOrderRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderApproveOrderRequest(val *OrderApproveOrderRequest) *NullableOrderApproveOrderRequest {
	return &NullableOrderApproveOrderRequest{value: val, isSet: true}
}

func (v NullableOrderApproveOrderRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderApproveOrderRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


