/*
order Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package order

import (
	"encoding/json"
	"fmt"
)

// checks if the OrderCreateRefundRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrderCreateRefundRequest{}

// OrderCreateRefundRequest struct for OrderCreateRefundRequest
type OrderCreateRefundRequest struct {
	TenantId string `json:"tenantId"`
	PaymentId string `json:"paymentId"`
	Items []OrderRefundItem `json:"items,omitempty"`
	Amounts []OrderRefundAmount `json:"amounts"`
	Note *string `json:"note,omitempty"`
	AdditionalInfo *string `json:"additionalInfo,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _OrderCreateRefundRequest OrderCreateRefundRequest

// NewOrderCreateRefundRequest instantiates a new OrderCreateRefundRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrderCreateRefundRequest(tenantId string, paymentId string, amounts []OrderRefundAmount) *OrderCreateRefundRequest {
	this := OrderCreateRefundRequest{}
	this.TenantId = tenantId
	this.PaymentId = paymentId
	this.Amounts = amounts
	return &this
}

// NewOrderCreateRefundRequestWithDefaults instantiates a new OrderCreateRefundRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrderCreateRefundRequestWithDefaults() *OrderCreateRefundRequest {
	this := OrderCreateRefundRequest{}
	return &this
}

// GetTenantId returns the TenantId field value
func (o *OrderCreateRefundRequest) GetTenantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *OrderCreateRefundRequest) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *OrderCreateRefundRequest) SetTenantId(v string) {
	o.TenantId = v
}

// GetPaymentId returns the PaymentId field value
func (o *OrderCreateRefundRequest) GetPaymentId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PaymentId
}

// GetPaymentIdOk returns a tuple with the PaymentId field value
// and a boolean to check if the value has been set.
func (o *OrderCreateRefundRequest) GetPaymentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PaymentId, true
}

// SetPaymentId sets field value
func (o *OrderCreateRefundRequest) SetPaymentId(v string) {
	o.PaymentId = v
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *OrderCreateRefundRequest) GetItems() []OrderRefundItem {
	if o == nil || IsNil(o.Items) {
		var ret []OrderRefundItem
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCreateRefundRequest) GetItemsOk() ([]OrderRefundItem, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// &#39;Has&#39;Items returns a boolean if a field has been set.
func (o *OrderCreateRefundRequest) &#39;Has&#39;Items() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []OrderRefundItem and assigns it to the Items field.
func (o *OrderCreateRefundRequest) SetItems(v []OrderRefundItem) {
	o.Items = v
}

// GetAmounts returns the Amounts field value
func (o *OrderCreateRefundRequest) GetAmounts() []OrderRefundAmount {
	if o == nil {
		var ret []OrderRefundAmount
		return ret
	}

	return o.Amounts
}

// GetAmountsOk returns a tuple with the Amounts field value
// and a boolean to check if the value has been set.
func (o *OrderCreateRefundRequest) GetAmountsOk() ([]OrderRefundAmount, bool) {
	if o == nil {
		return nil, false
	}
	return o.Amounts, true
}

// SetAmounts sets field value
func (o *OrderCreateRefundRequest) SetAmounts(v []OrderRefundAmount) {
	o.Amounts = v
}

// GetNote returns the Note field value if set, zero value otherwise.
func (o *OrderCreateRefundRequest) GetNote() string {
	if o == nil || IsNil(o.Note) {
		var ret string
		return ret
	}
	return *o.Note
}

// GetNoteOk returns a tuple with the Note field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCreateRefundRequest) GetNoteOk() (*string, bool) {
	if o == nil || IsNil(o.Note) {
		return nil, false
	}
	return o.Note, true
}

// &#39;Has&#39;Note returns a boolean if a field has been set.
func (o *OrderCreateRefundRequest) &#39;Has&#39;Note() bool {
	if o != nil && !IsNil(o.Note) {
		return true
	}

	return false
}

// SetNote gets a reference to the given string and assigns it to the Note field.
func (o *OrderCreateRefundRequest) SetNote(v string) {
	o.Note = &v
}

// GetAdditionalInfo returns the AdditionalInfo field value if set, zero value otherwise.
func (o *OrderCreateRefundRequest) GetAdditionalInfo() string {
	if o == nil || IsNil(o.AdditionalInfo) {
		var ret string
		return ret
	}
	return *o.AdditionalInfo
}

// GetAdditionalInfoOk returns a tuple with the AdditionalInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCreateRefundRequest) GetAdditionalInfoOk() (*string, bool) {
	if o == nil || IsNil(o.AdditionalInfo) {
		return nil, false
	}
	return o.AdditionalInfo, true
}

// &#39;Has&#39;AdditionalInfo returns a boolean if a field has been set.
func (o *OrderCreateRefundRequest) &#39;Has&#39;AdditionalInfo() bool {
	if o != nil && !IsNil(o.AdditionalInfo) {
		return true
	}

	return false
}

// SetAdditionalInfo gets a reference to the given string and assigns it to the AdditionalInfo field.
func (o *OrderCreateRefundRequest) SetAdditionalInfo(v string) {
	o.AdditionalInfo = &v
}

func (o OrderCreateRefundRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrderCreateRefundRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["tenantId"] = o.TenantId
	toSerialize["paymentId"] = o.PaymentId
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	toSerialize["amounts"] = o.Amounts
	if !IsNil(o.Note) {
		toSerialize["note"] = o.Note
	}
	if !IsNil(o.AdditionalInfo) {
		toSerialize["additionalInfo"] = o.AdditionalInfo
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *OrderCreateRefundRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tenantId",
		"paymentId",
		"amounts",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOrderCreateRefundRequest := _OrderCreateRefundRequest{}

	err = json.Unmarshal(data, &varOrderCreateRefundRequest)

	if err != nil {
		return err
	}

	*o = OrderCreateRefundRequest(varOrderCreateRefundRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "tenantId")
		delete(additionalProperties, "paymentId")
		delete(additionalProperties, "items")
		delete(additionalProperties, "amounts")
		delete(additionalProperties, "note")
		delete(additionalProperties, "additionalInfo")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

// GetValue returns the value of well-known types
func (o *OrderCreateRefundRequest) GetValue() interface{} {
	if o == nil || IsNil(o.Type) || IsNil(o.AdditionalProperties) {
		return nil
	}
	return o.AdditionalProperties["value"]
}
// SetValue populate the value of well-known types
func (o *OrderCreateRefundRequest) SetValue(value interface{}) {
	if o == nil || IsNil(o.Type) || IsNil(value) {
		return
	}
    if IsNil(o.AdditionalProperties) {
        o.AdditionalProperties = map[string]interface{}{}
    }
	o.AdditionalProperties["value"] = value
	return
}
type NullableOrderCreateRefundRequest struct {
	value *OrderCreateRefundRequest
	isSet bool
}

func (v NullableOrderCreateRefundRequest) Get() *OrderCreateRefundRequest {
	return v.value
}

func (v *NullableOrderCreateRefundRequest) Set(val *OrderCreateRefundRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderCreateRefundRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderCreateRefundRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderCreateRefundRequest(val *OrderCreateRefundRequest) *NullableOrderCreateRefundRequest {
	return &NullableOrderCreateRefundRequest{value: val, isSet: true}
}

func (v NullableOrderCreateRefundRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderCreateRefundRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


