/*
order Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package order

import (
	"encoding/json"
)

// checks if the OrderOrderDataItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrderOrderDataItem{}

// OrderOrderDataItem struct for OrderOrderDataItem
type OrderOrderDataItem struct {
	Id *string `json:"id,omitempty"`
	ProductGrn *string `json:"productGrn,omitempty"`
	QtyOrdered *int64 `json:"qtyOrdered,omitempty"`
	FreeQty *int64 `json:"freeQty,omitempty"`
	QtyCommitted *int64 `json:"qtyCommitted,omitempty"`
	UnitSalePrice *OrderMoney `json:"unitSalePrice,omitempty"`
	UnitListPrice *OrderMoney `json:"unitListPrice,omitempty"`
	UnitBasePrice *OrderMoney `json:"unitBasePrice,omitempty"`
	UnitVatAmount *OrderMoney `json:"unitVatAmount,omitempty"`
	RowSalePrice *OrderMoney `json:"rowSalePrice,omitempty"`
	RowListPrice *OrderMoney `json:"rowListPrice,omitempty"`
	RowVatAmount *OrderMoney `json:"rowVatAmount,omitempty"`
	DiscountAmount *OrderMoney `json:"discountAmount,omitempty"`
	RowBasePrice *OrderMoney `json:"rowBasePrice,omitempty"`
	UnitCustomPrice *OrderMoney `json:"unitCustomPrice,omitempty"`
	RowCustomPrice *OrderMoney `json:"rowCustomPrice,omitempty"`
	VatPercentage *float32 `json:"vatPercentage,omitempty"`
	VatInaccurate *bool `json:"vatInaccurate,omitempty"`
	VatCalculated *bool `json:"vatCalculated,omitempty"`
	ProductName *string `json:"productName,omitempty"`
	ProductCode *string `json:"productCode,omitempty"`
	ProductSku *string `json:"productSku,omitempty"`
	ProductOptions *string `json:"productOptions,omitempty"`
	ProductImg *string `json:"productImg,omitempty"`
	ProductData *string `json:"productData,omitempty"`
	ShipmentInfoReference *string `json:"shipmentInfoReference,omitempty"`
	PromotionGrn []string `json:"promotionGrn,omitempty"`
	ProductIsVirtual *bool `json:"productIsVirtual,omitempty"`
	ProductConfiguration []ItemProductConfigurationStep `json:"productConfiguration,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _OrderOrderDataItem OrderOrderDataItem

// NewOrderOrderDataItem instantiates a new OrderOrderDataItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrderOrderDataItem() *OrderOrderDataItem {
	this := OrderOrderDataItem{}
	return &this
}

// NewOrderOrderDataItemWithDefaults instantiates a new OrderOrderDataItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrderOrderDataItemWithDefaults() *OrderOrderDataItem {
	this := OrderOrderDataItem{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *OrderOrderDataItem) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderOrderDataItem) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// &#39;Has&#39;Id returns a boolean if a field has been set.
func (o *OrderOrderDataItem) &#39;Has&#39;Id() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *OrderOrderDataItem) SetId(v string) {
	o.Id = &v
}

// GetProductGrn returns the ProductGrn field value if set, zero value otherwise.
func (o *OrderOrderDataItem) GetProductGrn() string {
	if o == nil || IsNil(o.ProductGrn) {
		var ret string
		return ret
	}
	return *o.ProductGrn
}

// GetProductGrnOk returns a tuple with the ProductGrn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderOrderDataItem) GetProductGrnOk() (*string, bool) {
	if o == nil || IsNil(o.ProductGrn) {
		return nil, false
	}
	return o.ProductGrn, true
}

// &#39;Has&#39;ProductGrn returns a boolean if a field has been set.
func (o *OrderOrderDataItem) &#39;Has&#39;ProductGrn() bool {
	if o != nil && !IsNil(o.ProductGrn) {
		return true
	}

	return false
}

// SetProductGrn gets a reference to the given string and assigns it to the ProductGrn field.
func (o *OrderOrderDataItem) SetProductGrn(v string) {
	o.ProductGrn = &v
}

// GetQtyOrdered returns the QtyOrdered field value if set, zero value otherwise.
func (o *OrderOrderDataItem) GetQtyOrdered() int64 {
	if o == nil || IsNil(o.QtyOrdered) {
		var ret int64
		return ret
	}
	return *o.QtyOrdered
}

// GetQtyOrderedOk returns a tuple with the QtyOrdered field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderOrderDataItem) GetQtyOrderedOk() (*int64, bool) {
	if o == nil || IsNil(o.QtyOrdered) {
		return nil, false
	}
	return o.QtyOrdered, true
}

// &#39;Has&#39;QtyOrdered returns a boolean if a field has been set.
func (o *OrderOrderDataItem) &#39;Has&#39;QtyOrdered() bool {
	if o != nil && !IsNil(o.QtyOrdered) {
		return true
	}

	return false
}

// SetQtyOrdered gets a reference to the given int64 and assigns it to the QtyOrdered field.
func (o *OrderOrderDataItem) SetQtyOrdered(v int64) {
	o.QtyOrdered = &v
}

// GetFreeQty returns the FreeQty field value if set, zero value otherwise.
func (o *OrderOrderDataItem) GetFreeQty() int64 {
	if o == nil || IsNil(o.FreeQty) {
		var ret int64
		return ret
	}
	return *o.FreeQty
}

// GetFreeQtyOk returns a tuple with the FreeQty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderOrderDataItem) GetFreeQtyOk() (*int64, bool) {
	if o == nil || IsNil(o.FreeQty) {
		return nil, false
	}
	return o.FreeQty, true
}

// &#39;Has&#39;FreeQty returns a boolean if a field has been set.
func (o *OrderOrderDataItem) &#39;Has&#39;FreeQty() bool {
	if o != nil && !IsNil(o.FreeQty) {
		return true
	}

	return false
}

// SetFreeQty gets a reference to the given int64 and assigns it to the FreeQty field.
func (o *OrderOrderDataItem) SetFreeQty(v int64) {
	o.FreeQty = &v
}

// GetQtyCommitted returns the QtyCommitted field value if set, zero value otherwise.
func (o *OrderOrderDataItem) GetQtyCommitted() int64 {
	if o == nil || IsNil(o.QtyCommitted) {
		var ret int64
		return ret
	}
	return *o.QtyCommitted
}

// GetQtyCommittedOk returns a tuple with the QtyCommitted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderOrderDataItem) GetQtyCommittedOk() (*int64, bool) {
	if o == nil || IsNil(o.QtyCommitted) {
		return nil, false
	}
	return o.QtyCommitted, true
}

// &#39;Has&#39;QtyCommitted returns a boolean if a field has been set.
func (o *OrderOrderDataItem) &#39;Has&#39;QtyCommitted() bool {
	if o != nil && !IsNil(o.QtyCommitted) {
		return true
	}

	return false
}

// SetQtyCommitted gets a reference to the given int64 and assigns it to the QtyCommitted field.
func (o *OrderOrderDataItem) SetQtyCommitted(v int64) {
	o.QtyCommitted = &v
}

// GetUnitSalePrice returns the UnitSalePrice field value if set, zero value otherwise.
func (o *OrderOrderDataItem) GetUnitSalePrice() OrderMoney {
	if o == nil || IsNil(o.UnitSalePrice) {
		var ret OrderMoney
		return ret
	}
	return *o.UnitSalePrice
}

// GetUnitSalePriceOk returns a tuple with the UnitSalePrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderOrderDataItem) GetUnitSalePriceOk() (*OrderMoney, bool) {
	if o == nil || IsNil(o.UnitSalePrice) {
		return nil, false
	}
	return o.UnitSalePrice, true
}

// &#39;Has&#39;UnitSalePrice returns a boolean if a field has been set.
func (o *OrderOrderDataItem) &#39;Has&#39;UnitSalePrice() bool {
	if o != nil && !IsNil(o.UnitSalePrice) {
		return true
	}

	return false
}

// SetUnitSalePrice gets a reference to the given OrderMoney and assigns it to the UnitSalePrice field.
func (o *OrderOrderDataItem) SetUnitSalePrice(v OrderMoney) {
	o.UnitSalePrice = &v
}

// GetUnitListPrice returns the UnitListPrice field value if set, zero value otherwise.
func (o *OrderOrderDataItem) GetUnitListPrice() OrderMoney {
	if o == nil || IsNil(o.UnitListPrice) {
		var ret OrderMoney
		return ret
	}
	return *o.UnitListPrice
}

// GetUnitListPriceOk returns a tuple with the UnitListPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderOrderDataItem) GetUnitListPriceOk() (*OrderMoney, bool) {
	if o == nil || IsNil(o.UnitListPrice) {
		return nil, false
	}
	return o.UnitListPrice, true
}

// &#39;Has&#39;UnitListPrice returns a boolean if a field has been set.
func (o *OrderOrderDataItem) &#39;Has&#39;UnitListPrice() bool {
	if o != nil && !IsNil(o.UnitListPrice) {
		return true
	}

	return false
}

// SetUnitListPrice gets a reference to the given OrderMoney and assigns it to the UnitListPrice field.
func (o *OrderOrderDataItem) SetUnitListPrice(v OrderMoney) {
	o.UnitListPrice = &v
}

// GetUnitBasePrice returns the UnitBasePrice field value if set, zero value otherwise.
func (o *OrderOrderDataItem) GetUnitBasePrice() OrderMoney {
	if o == nil || IsNil(o.UnitBasePrice) {
		var ret OrderMoney
		return ret
	}
	return *o.UnitBasePrice
}

// GetUnitBasePriceOk returns a tuple with the UnitBasePrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderOrderDataItem) GetUnitBasePriceOk() (*OrderMoney, bool) {
	if o == nil || IsNil(o.UnitBasePrice) {
		return nil, false
	}
	return o.UnitBasePrice, true
}

// &#39;Has&#39;UnitBasePrice returns a boolean if a field has been set.
func (o *OrderOrderDataItem) &#39;Has&#39;UnitBasePrice() bool {
	if o != nil && !IsNil(o.UnitBasePrice) {
		return true
	}

	return false
}

// SetUnitBasePrice gets a reference to the given OrderMoney and assigns it to the UnitBasePrice field.
func (o *OrderOrderDataItem) SetUnitBasePrice(v OrderMoney) {
	o.UnitBasePrice = &v
}

// GetUnitVatAmount returns the UnitVatAmount field value if set, zero value otherwise.
func (o *OrderOrderDataItem) GetUnitVatAmount() OrderMoney {
	if o == nil || IsNil(o.UnitVatAmount) {
		var ret OrderMoney
		return ret
	}
	return *o.UnitVatAmount
}

// GetUnitVatAmountOk returns a tuple with the UnitVatAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderOrderDataItem) GetUnitVatAmountOk() (*OrderMoney, bool) {
	if o == nil || IsNil(o.UnitVatAmount) {
		return nil, false
	}
	return o.UnitVatAmount, true
}

// &#39;Has&#39;UnitVatAmount returns a boolean if a field has been set.
func (o *OrderOrderDataItem) &#39;Has&#39;UnitVatAmount() bool {
	if o != nil && !IsNil(o.UnitVatAmount) {
		return true
	}

	return false
}

// SetUnitVatAmount gets a reference to the given OrderMoney and assigns it to the UnitVatAmount field.
func (o *OrderOrderDataItem) SetUnitVatAmount(v OrderMoney) {
	o.UnitVatAmount = &v
}

// GetRowSalePrice returns the RowSalePrice field value if set, zero value otherwise.
func (o *OrderOrderDataItem) GetRowSalePrice() OrderMoney {
	if o == nil || IsNil(o.RowSalePrice) {
		var ret OrderMoney
		return ret
	}
	return *o.RowSalePrice
}

// GetRowSalePriceOk returns a tuple with the RowSalePrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderOrderDataItem) GetRowSalePriceOk() (*OrderMoney, bool) {
	if o == nil || IsNil(o.RowSalePrice) {
		return nil, false
	}
	return o.RowSalePrice, true
}

// &#39;Has&#39;RowSalePrice returns a boolean if a field has been set.
func (o *OrderOrderDataItem) &#39;Has&#39;RowSalePrice() bool {
	if o != nil && !IsNil(o.RowSalePrice) {
		return true
	}

	return false
}

// SetRowSalePrice gets a reference to the given OrderMoney and assigns it to the RowSalePrice field.
func (o *OrderOrderDataItem) SetRowSalePrice(v OrderMoney) {
	o.RowSalePrice = &v
}

// GetRowListPrice returns the RowListPrice field value if set, zero value otherwise.
func (o *OrderOrderDataItem) GetRowListPrice() OrderMoney {
	if o == nil || IsNil(o.RowListPrice) {
		var ret OrderMoney
		return ret
	}
	return *o.RowListPrice
}

// GetRowListPriceOk returns a tuple with the RowListPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderOrderDataItem) GetRowListPriceOk() (*OrderMoney, bool) {
	if o == nil || IsNil(o.RowListPrice) {
		return nil, false
	}
	return o.RowListPrice, true
}

// &#39;Has&#39;RowListPrice returns a boolean if a field has been set.
func (o *OrderOrderDataItem) &#39;Has&#39;RowListPrice() bool {
	if o != nil && !IsNil(o.RowListPrice) {
		return true
	}

	return false
}

// SetRowListPrice gets a reference to the given OrderMoney and assigns it to the RowListPrice field.
func (o *OrderOrderDataItem) SetRowListPrice(v OrderMoney) {
	o.RowListPrice = &v
}

// GetRowVatAmount returns the RowVatAmount field value if set, zero value otherwise.
func (o *OrderOrderDataItem) GetRowVatAmount() OrderMoney {
	if o == nil || IsNil(o.RowVatAmount) {
		var ret OrderMoney
		return ret
	}
	return *o.RowVatAmount
}

// GetRowVatAmountOk returns a tuple with the RowVatAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderOrderDataItem) GetRowVatAmountOk() (*OrderMoney, bool) {
	if o == nil || IsNil(o.RowVatAmount) {
		return nil, false
	}
	return o.RowVatAmount, true
}

// &#39;Has&#39;RowVatAmount returns a boolean if a field has been set.
func (o *OrderOrderDataItem) &#39;Has&#39;RowVatAmount() bool {
	if o != nil && !IsNil(o.RowVatAmount) {
		return true
	}

	return false
}

// SetRowVatAmount gets a reference to the given OrderMoney and assigns it to the RowVatAmount field.
func (o *OrderOrderDataItem) SetRowVatAmount(v OrderMoney) {
	o.RowVatAmount = &v
}

// GetDiscountAmount returns the DiscountAmount field value if set, zero value otherwise.
func (o *OrderOrderDataItem) GetDiscountAmount() OrderMoney {
	if o == nil || IsNil(o.DiscountAmount) {
		var ret OrderMoney
		return ret
	}
	return *o.DiscountAmount
}

// GetDiscountAmountOk returns a tuple with the DiscountAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderOrderDataItem) GetDiscountAmountOk() (*OrderMoney, bool) {
	if o == nil || IsNil(o.DiscountAmount) {
		return nil, false
	}
	return o.DiscountAmount, true
}

// &#39;Has&#39;DiscountAmount returns a boolean if a field has been set.
func (o *OrderOrderDataItem) &#39;Has&#39;DiscountAmount() bool {
	if o != nil && !IsNil(o.DiscountAmount) {
		return true
	}

	return false
}

// SetDiscountAmount gets a reference to the given OrderMoney and assigns it to the DiscountAmount field.
func (o *OrderOrderDataItem) SetDiscountAmount(v OrderMoney) {
	o.DiscountAmount = &v
}

// GetRowBasePrice returns the RowBasePrice field value if set, zero value otherwise.
func (o *OrderOrderDataItem) GetRowBasePrice() OrderMoney {
	if o == nil || IsNil(o.RowBasePrice) {
		var ret OrderMoney
		return ret
	}
	return *o.RowBasePrice
}

// GetRowBasePriceOk returns a tuple with the RowBasePrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderOrderDataItem) GetRowBasePriceOk() (*OrderMoney, bool) {
	if o == nil || IsNil(o.RowBasePrice) {
		return nil, false
	}
	return o.RowBasePrice, true
}

// &#39;Has&#39;RowBasePrice returns a boolean if a field has been set.
func (o *OrderOrderDataItem) &#39;Has&#39;RowBasePrice() bool {
	if o != nil && !IsNil(o.RowBasePrice) {
		return true
	}

	return false
}

// SetRowBasePrice gets a reference to the given OrderMoney and assigns it to the RowBasePrice field.
func (o *OrderOrderDataItem) SetRowBasePrice(v OrderMoney) {
	o.RowBasePrice = &v
}

// GetUnitCustomPrice returns the UnitCustomPrice field value if set, zero value otherwise.
func (o *OrderOrderDataItem) GetUnitCustomPrice() OrderMoney {
	if o == nil || IsNil(o.UnitCustomPrice) {
		var ret OrderMoney
		return ret
	}
	return *o.UnitCustomPrice
}

// GetUnitCustomPriceOk returns a tuple with the UnitCustomPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderOrderDataItem) GetUnitCustomPriceOk() (*OrderMoney, bool) {
	if o == nil || IsNil(o.UnitCustomPrice) {
		return nil, false
	}
	return o.UnitCustomPrice, true
}

// &#39;Has&#39;UnitCustomPrice returns a boolean if a field has been set.
func (o *OrderOrderDataItem) &#39;Has&#39;UnitCustomPrice() bool {
	if o != nil && !IsNil(o.UnitCustomPrice) {
		return true
	}

	return false
}

// SetUnitCustomPrice gets a reference to the given OrderMoney and assigns it to the UnitCustomPrice field.
func (o *OrderOrderDataItem) SetUnitCustomPrice(v OrderMoney) {
	o.UnitCustomPrice = &v
}

// GetRowCustomPrice returns the RowCustomPrice field value if set, zero value otherwise.
func (o *OrderOrderDataItem) GetRowCustomPrice() OrderMoney {
	if o == nil || IsNil(o.RowCustomPrice) {
		var ret OrderMoney
		return ret
	}
	return *o.RowCustomPrice
}

// GetRowCustomPriceOk returns a tuple with the RowCustomPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderOrderDataItem) GetRowCustomPriceOk() (*OrderMoney, bool) {
	if o == nil || IsNil(o.RowCustomPrice) {
		return nil, false
	}
	return o.RowCustomPrice, true
}

// &#39;Has&#39;RowCustomPrice returns a boolean if a field has been set.
func (o *OrderOrderDataItem) &#39;Has&#39;RowCustomPrice() bool {
	if o != nil && !IsNil(o.RowCustomPrice) {
		return true
	}

	return false
}

// SetRowCustomPrice gets a reference to the given OrderMoney and assigns it to the RowCustomPrice field.
func (o *OrderOrderDataItem) SetRowCustomPrice(v OrderMoney) {
	o.RowCustomPrice = &v
}

// GetVatPercentage returns the VatPercentage field value if set, zero value otherwise.
func (o *OrderOrderDataItem) GetVatPercentage() float32 {
	if o == nil || IsNil(o.VatPercentage) {
		var ret float32
		return ret
	}
	return *o.VatPercentage
}

// GetVatPercentageOk returns a tuple with the VatPercentage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderOrderDataItem) GetVatPercentageOk() (*float32, bool) {
	if o == nil || IsNil(o.VatPercentage) {
		return nil, false
	}
	return o.VatPercentage, true
}

// &#39;Has&#39;VatPercentage returns a boolean if a field has been set.
func (o *OrderOrderDataItem) &#39;Has&#39;VatPercentage() bool {
	if o != nil && !IsNil(o.VatPercentage) {
		return true
	}

	return false
}

// SetVatPercentage gets a reference to the given float32 and assigns it to the VatPercentage field.
func (o *OrderOrderDataItem) SetVatPercentage(v float32) {
	o.VatPercentage = &v
}

// GetVatInaccurate returns the VatInaccurate field value if set, zero value otherwise.
func (o *OrderOrderDataItem) GetVatInaccurate() bool {
	if o == nil || IsNil(o.VatInaccurate) {
		var ret bool
		return ret
	}
	return *o.VatInaccurate
}

// GetVatInaccurateOk returns a tuple with the VatInaccurate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderOrderDataItem) GetVatInaccurateOk() (*bool, bool) {
	if o == nil || IsNil(o.VatInaccurate) {
		return nil, false
	}
	return o.VatInaccurate, true
}

// &#39;Has&#39;VatInaccurate returns a boolean if a field has been set.
func (o *OrderOrderDataItem) &#39;Has&#39;VatInaccurate() bool {
	if o != nil && !IsNil(o.VatInaccurate) {
		return true
	}

	return false
}

// SetVatInaccurate gets a reference to the given bool and assigns it to the VatInaccurate field.
func (o *OrderOrderDataItem) SetVatInaccurate(v bool) {
	o.VatInaccurate = &v
}

// GetVatCalculated returns the VatCalculated field value if set, zero value otherwise.
func (o *OrderOrderDataItem) GetVatCalculated() bool {
	if o == nil || IsNil(o.VatCalculated) {
		var ret bool
		return ret
	}
	return *o.VatCalculated
}

// GetVatCalculatedOk returns a tuple with the VatCalculated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderOrderDataItem) GetVatCalculatedOk() (*bool, bool) {
	if o == nil || IsNil(o.VatCalculated) {
		return nil, false
	}
	return o.VatCalculated, true
}

// &#39;Has&#39;VatCalculated returns a boolean if a field has been set.
func (o *OrderOrderDataItem) &#39;Has&#39;VatCalculated() bool {
	if o != nil && !IsNil(o.VatCalculated) {
		return true
	}

	return false
}

// SetVatCalculated gets a reference to the given bool and assigns it to the VatCalculated field.
func (o *OrderOrderDataItem) SetVatCalculated(v bool) {
	o.VatCalculated = &v
}

// GetProductName returns the ProductName field value if set, zero value otherwise.
func (o *OrderOrderDataItem) GetProductName() string {
	if o == nil || IsNil(o.ProductName) {
		var ret string
		return ret
	}
	return *o.ProductName
}

// GetProductNameOk returns a tuple with the ProductName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderOrderDataItem) GetProductNameOk() (*string, bool) {
	if o == nil || IsNil(o.ProductName) {
		return nil, false
	}
	return o.ProductName, true
}

// &#39;Has&#39;ProductName returns a boolean if a field has been set.
func (o *OrderOrderDataItem) &#39;Has&#39;ProductName() bool {
	if o != nil && !IsNil(o.ProductName) {
		return true
	}

	return false
}

// SetProductName gets a reference to the given string and assigns it to the ProductName field.
func (o *OrderOrderDataItem) SetProductName(v string) {
	o.ProductName = &v
}

// GetProductCode returns the ProductCode field value if set, zero value otherwise.
func (o *OrderOrderDataItem) GetProductCode() string {
	if o == nil || IsNil(o.ProductCode) {
		var ret string
		return ret
	}
	return *o.ProductCode
}

// GetProductCodeOk returns a tuple with the ProductCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderOrderDataItem) GetProductCodeOk() (*string, bool) {
	if o == nil || IsNil(o.ProductCode) {
		return nil, false
	}
	return o.ProductCode, true
}

// &#39;Has&#39;ProductCode returns a boolean if a field has been set.
func (o *OrderOrderDataItem) &#39;Has&#39;ProductCode() bool {
	if o != nil && !IsNil(o.ProductCode) {
		return true
	}

	return false
}

// SetProductCode gets a reference to the given string and assigns it to the ProductCode field.
func (o *OrderOrderDataItem) SetProductCode(v string) {
	o.ProductCode = &v
}

// GetProductSku returns the ProductSku field value if set, zero value otherwise.
func (o *OrderOrderDataItem) GetProductSku() string {
	if o == nil || IsNil(o.ProductSku) {
		var ret string
		return ret
	}
	return *o.ProductSku
}

// GetProductSkuOk returns a tuple with the ProductSku field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderOrderDataItem) GetProductSkuOk() (*string, bool) {
	if o == nil || IsNil(o.ProductSku) {
		return nil, false
	}
	return o.ProductSku, true
}

// &#39;Has&#39;ProductSku returns a boolean if a field has been set.
func (o *OrderOrderDataItem) &#39;Has&#39;ProductSku() bool {
	if o != nil && !IsNil(o.ProductSku) {
		return true
	}

	return false
}

// SetProductSku gets a reference to the given string and assigns it to the ProductSku field.
func (o *OrderOrderDataItem) SetProductSku(v string) {
	o.ProductSku = &v
}

// GetProductOptions returns the ProductOptions field value if set, zero value otherwise.
func (o *OrderOrderDataItem) GetProductOptions() string {
	if o == nil || IsNil(o.ProductOptions) {
		var ret string
		return ret
	}
	return *o.ProductOptions
}

// GetProductOptionsOk returns a tuple with the ProductOptions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderOrderDataItem) GetProductOptionsOk() (*string, bool) {
	if o == nil || IsNil(o.ProductOptions) {
		return nil, false
	}
	return o.ProductOptions, true
}

// &#39;Has&#39;ProductOptions returns a boolean if a field has been set.
func (o *OrderOrderDataItem) &#39;Has&#39;ProductOptions() bool {
	if o != nil && !IsNil(o.ProductOptions) {
		return true
	}

	return false
}

// SetProductOptions gets a reference to the given string and assigns it to the ProductOptions field.
func (o *OrderOrderDataItem) SetProductOptions(v string) {
	o.ProductOptions = &v
}

// GetProductImg returns the ProductImg field value if set, zero value otherwise.
func (o *OrderOrderDataItem) GetProductImg() string {
	if o == nil || IsNil(o.ProductImg) {
		var ret string
		return ret
	}
	return *o.ProductImg
}

// GetProductImgOk returns a tuple with the ProductImg field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderOrderDataItem) GetProductImgOk() (*string, bool) {
	if o == nil || IsNil(o.ProductImg) {
		return nil, false
	}
	return o.ProductImg, true
}

// &#39;Has&#39;ProductImg returns a boolean if a field has been set.
func (o *OrderOrderDataItem) &#39;Has&#39;ProductImg() bool {
	if o != nil && !IsNil(o.ProductImg) {
		return true
	}

	return false
}

// SetProductImg gets a reference to the given string and assigns it to the ProductImg field.
func (o *OrderOrderDataItem) SetProductImg(v string) {
	o.ProductImg = &v
}

// GetProductData returns the ProductData field value if set, zero value otherwise.
func (o *OrderOrderDataItem) GetProductData() string {
	if o == nil || IsNil(o.ProductData) {
		var ret string
		return ret
	}
	return *o.ProductData
}

// GetProductDataOk returns a tuple with the ProductData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderOrderDataItem) GetProductDataOk() (*string, bool) {
	if o == nil || IsNil(o.ProductData) {
		return nil, false
	}
	return o.ProductData, true
}

// &#39;Has&#39;ProductData returns a boolean if a field has been set.
func (o *OrderOrderDataItem) &#39;Has&#39;ProductData() bool {
	if o != nil && !IsNil(o.ProductData) {
		return true
	}

	return false
}

// SetProductData gets a reference to the given string and assigns it to the ProductData field.
func (o *OrderOrderDataItem) SetProductData(v string) {
	o.ProductData = &v
}

// GetShipmentInfoReference returns the ShipmentInfoReference field value if set, zero value otherwise.
func (o *OrderOrderDataItem) GetShipmentInfoReference() string {
	if o == nil || IsNil(o.ShipmentInfoReference) {
		var ret string
		return ret
	}
	return *o.ShipmentInfoReference
}

// GetShipmentInfoReferenceOk returns a tuple with the ShipmentInfoReference field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderOrderDataItem) GetShipmentInfoReferenceOk() (*string, bool) {
	if o == nil || IsNil(o.ShipmentInfoReference) {
		return nil, false
	}
	return o.ShipmentInfoReference, true
}

// &#39;Has&#39;ShipmentInfoReference returns a boolean if a field has been set.
func (o *OrderOrderDataItem) &#39;Has&#39;ShipmentInfoReference() bool {
	if o != nil && !IsNil(o.ShipmentInfoReference) {
		return true
	}

	return false
}

// SetShipmentInfoReference gets a reference to the given string and assigns it to the ShipmentInfoReference field.
func (o *OrderOrderDataItem) SetShipmentInfoReference(v string) {
	o.ShipmentInfoReference = &v
}

// GetPromotionGrn returns the PromotionGrn field value if set, zero value otherwise.
func (o *OrderOrderDataItem) GetPromotionGrn() []string {
	if o == nil || IsNil(o.PromotionGrn) {
		var ret []string
		return ret
	}
	return o.PromotionGrn
}

// GetPromotionGrnOk returns a tuple with the PromotionGrn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderOrderDataItem) GetPromotionGrnOk() ([]string, bool) {
	if o == nil || IsNil(o.PromotionGrn) {
		return nil, false
	}
	return o.PromotionGrn, true
}

// &#39;Has&#39;PromotionGrn returns a boolean if a field has been set.
func (o *OrderOrderDataItem) &#39;Has&#39;PromotionGrn() bool {
	if o != nil && !IsNil(o.PromotionGrn) {
		return true
	}

	return false
}

// SetPromotionGrn gets a reference to the given []string and assigns it to the PromotionGrn field.
func (o *OrderOrderDataItem) SetPromotionGrn(v []string) {
	o.PromotionGrn = v
}

// GetProductIsVirtual returns the ProductIsVirtual field value if set, zero value otherwise.
func (o *OrderOrderDataItem) GetProductIsVirtual() bool {
	if o == nil || IsNil(o.ProductIsVirtual) {
		var ret bool
		return ret
	}
	return *o.ProductIsVirtual
}

// GetProductIsVirtualOk returns a tuple with the ProductIsVirtual field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderOrderDataItem) GetProductIsVirtualOk() (*bool, bool) {
	if o == nil || IsNil(o.ProductIsVirtual) {
		return nil, false
	}
	return o.ProductIsVirtual, true
}

// &#39;Has&#39;ProductIsVirtual returns a boolean if a field has been set.
func (o *OrderOrderDataItem) &#39;Has&#39;ProductIsVirtual() bool {
	if o != nil && !IsNil(o.ProductIsVirtual) {
		return true
	}

	return false
}

// SetProductIsVirtual gets a reference to the given bool and assigns it to the ProductIsVirtual field.
func (o *OrderOrderDataItem) SetProductIsVirtual(v bool) {
	o.ProductIsVirtual = &v
}

// GetProductConfiguration returns the ProductConfiguration field value if set, zero value otherwise.
func (o *OrderOrderDataItem) GetProductConfiguration() []ItemProductConfigurationStep {
	if o == nil || IsNil(o.ProductConfiguration) {
		var ret []ItemProductConfigurationStep
		return ret
	}
	return o.ProductConfiguration
}

// GetProductConfigurationOk returns a tuple with the ProductConfiguration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderOrderDataItem) GetProductConfigurationOk() ([]ItemProductConfigurationStep, bool) {
	if o == nil || IsNil(o.ProductConfiguration) {
		return nil, false
	}
	return o.ProductConfiguration, true
}

// &#39;Has&#39;ProductConfiguration returns a boolean if a field has been set.
func (o *OrderOrderDataItem) &#39;Has&#39;ProductConfiguration() bool {
	if o != nil && !IsNil(o.ProductConfiguration) {
		return true
	}

	return false
}

// SetProductConfiguration gets a reference to the given []ItemProductConfigurationStep and assigns it to the ProductConfiguration field.
func (o *OrderOrderDataItem) SetProductConfiguration(v []ItemProductConfigurationStep) {
	o.ProductConfiguration = v
}

func (o OrderOrderDataItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrderOrderDataItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.ProductGrn) {
		toSerialize["productGrn"] = o.ProductGrn
	}
	if !IsNil(o.QtyOrdered) {
		toSerialize["qtyOrdered"] = o.QtyOrdered
	}
	if !IsNil(o.FreeQty) {
		toSerialize["freeQty"] = o.FreeQty
	}
	if !IsNil(o.QtyCommitted) {
		toSerialize["qtyCommitted"] = o.QtyCommitted
	}
	if !IsNil(o.UnitSalePrice) {
		toSerialize["unitSalePrice"] = o.UnitSalePrice
	}
	if !IsNil(o.UnitListPrice) {
		toSerialize["unitListPrice"] = o.UnitListPrice
	}
	if !IsNil(o.UnitBasePrice) {
		toSerialize["unitBasePrice"] = o.UnitBasePrice
	}
	if !IsNil(o.UnitVatAmount) {
		toSerialize["unitVatAmount"] = o.UnitVatAmount
	}
	if !IsNil(o.RowSalePrice) {
		toSerialize["rowSalePrice"] = o.RowSalePrice
	}
	if !IsNil(o.RowListPrice) {
		toSerialize["rowListPrice"] = o.RowListPrice
	}
	if !IsNil(o.RowVatAmount) {
		toSerialize["rowVatAmount"] = o.RowVatAmount
	}
	if !IsNil(o.DiscountAmount) {
		toSerialize["discountAmount"] = o.DiscountAmount
	}
	if !IsNil(o.RowBasePrice) {
		toSerialize["rowBasePrice"] = o.RowBasePrice
	}
	if !IsNil(o.UnitCustomPrice) {
		toSerialize["unitCustomPrice"] = o.UnitCustomPrice
	}
	if !IsNil(o.RowCustomPrice) {
		toSerialize["rowCustomPrice"] = o.RowCustomPrice
	}
	if !IsNil(o.VatPercentage) {
		toSerialize["vatPercentage"] = o.VatPercentage
	}
	if !IsNil(o.VatInaccurate) {
		toSerialize["vatInaccurate"] = o.VatInaccurate
	}
	if !IsNil(o.VatCalculated) {
		toSerialize["vatCalculated"] = o.VatCalculated
	}
	if !IsNil(o.ProductName) {
		toSerialize["productName"] = o.ProductName
	}
	if !IsNil(o.ProductCode) {
		toSerialize["productCode"] = o.ProductCode
	}
	if !IsNil(o.ProductSku) {
		toSerialize["productSku"] = o.ProductSku
	}
	if !IsNil(o.ProductOptions) {
		toSerialize["productOptions"] = o.ProductOptions
	}
	if !IsNil(o.ProductImg) {
		toSerialize["productImg"] = o.ProductImg
	}
	if !IsNil(o.ProductData) {
		toSerialize["productData"] = o.ProductData
	}
	if !IsNil(o.ShipmentInfoReference) {
		toSerialize["shipmentInfoReference"] = o.ShipmentInfoReference
	}
	if !IsNil(o.PromotionGrn) {
		toSerialize["promotionGrn"] = o.PromotionGrn
	}
	if !IsNil(o.ProductIsVirtual) {
		toSerialize["productIsVirtual"] = o.ProductIsVirtual
	}
	if !IsNil(o.ProductConfiguration) {
		toSerialize["productConfiguration"] = o.ProductConfiguration
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *OrderOrderDataItem) UnmarshalJSON(data []byte) (err error) {
	varOrderOrderDataItem := _OrderOrderDataItem{}

	err = json.Unmarshal(data, &varOrderOrderDataItem)

	if err != nil {
		return err
	}

	*o = OrderOrderDataItem(varOrderOrderDataItem)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "productGrn")
		delete(additionalProperties, "qtyOrdered")
		delete(additionalProperties, "freeQty")
		delete(additionalProperties, "qtyCommitted")
		delete(additionalProperties, "unitSalePrice")
		delete(additionalProperties, "unitListPrice")
		delete(additionalProperties, "unitBasePrice")
		delete(additionalProperties, "unitVatAmount")
		delete(additionalProperties, "rowSalePrice")
		delete(additionalProperties, "rowListPrice")
		delete(additionalProperties, "rowVatAmount")
		delete(additionalProperties, "discountAmount")
		delete(additionalProperties, "rowBasePrice")
		delete(additionalProperties, "unitCustomPrice")
		delete(additionalProperties, "rowCustomPrice")
		delete(additionalProperties, "vatPercentage")
		delete(additionalProperties, "vatInaccurate")
		delete(additionalProperties, "vatCalculated")
		delete(additionalProperties, "productName")
		delete(additionalProperties, "productCode")
		delete(additionalProperties, "productSku")
		delete(additionalProperties, "productOptions")
		delete(additionalProperties, "productImg")
		delete(additionalProperties, "productData")
		delete(additionalProperties, "shipmentInfoReference")
		delete(additionalProperties, "promotionGrn")
		delete(additionalProperties, "productIsVirtual")
		delete(additionalProperties, "productConfiguration")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

// GetValue returns the value of well-known types
func (o *OrderOrderDataItem) GetValue() interface{} {
	if o == nil || IsNil(o.Type) || IsNil(o.AdditionalProperties) {
		return nil
	}
	return o.AdditionalProperties["value"]
}
// SetValue populate the value of well-known types
func (o *OrderOrderDataItem) SetValue(value interface{}) {
	if o == nil || IsNil(o.Type) || IsNil(value) {
		return
	}
    if IsNil(o.AdditionalProperties) {
        o.AdditionalProperties = map[string]interface{}{}
    }
	o.AdditionalProperties["value"] = value
	return
}
type NullableOrderOrderDataItem struct {
	value *OrderOrderDataItem
	isSet bool
}

func (v NullableOrderOrderDataItem) Get() *OrderOrderDataItem {
	return v.value
}

func (v *NullableOrderOrderDataItem) Set(val *OrderOrderDataItem) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderOrderDataItem) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderOrderDataItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderOrderDataItem(val *OrderOrderDataItem) *NullableOrderOrderDataItem {
	return &NullableOrderOrderDataItem{value: val, isSet: true}
}

func (v NullableOrderOrderDataItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderOrderDataItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


