/*
order Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package order

import (
	"encoding/json"
)

// checks if the OrderGetOrderRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrderGetOrderRequest{}

// OrderGetOrderRequest struct for OrderGetOrderRequest
type OrderGetOrderRequest struct {
	TenantId *string `json:"tenantId,omitempty"`
	Id *string `json:"id,omitempty"`
}

// NewOrderGetOrderRequest instantiates a new OrderGetOrderRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrderGetOrderRequest() *OrderGetOrderRequest {
	this := OrderGetOrderRequest{}
	return &this
}

// NewOrderGetOrderRequestWithDefaults instantiates a new OrderGetOrderRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrderGetOrderRequestWithDefaults() *OrderGetOrderRequest {
	this := OrderGetOrderRequest{}
	return &this
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *OrderGetOrderRequest) GetTenantId() string {
	if o == nil || IsNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderGetOrderRequest) GetTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *OrderGetOrderRequest) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *OrderGetOrderRequest) SetTenantId(v string) {
	o.TenantId = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *OrderGetOrderRequest) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderGetOrderRequest) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *OrderGetOrderRequest) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *OrderGetOrderRequest) SetId(v string) {
	o.Id = &v
}

func (o OrderGetOrderRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrderGetOrderRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TenantId) {
		toSerialize["tenantId"] = o.TenantId
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return toSerialize, nil
}

type NullableOrderGetOrderRequest struct {
	value *OrderGetOrderRequest
	isSet bool
}

func (v NullableOrderGetOrderRequest) Get() *OrderGetOrderRequest {
	return v.value
}

func (v *NullableOrderGetOrderRequest) Set(val *OrderGetOrderRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderGetOrderRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderGetOrderRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderGetOrderRequest(val *OrderGetOrderRequest) *NullableOrderGetOrderRequest {
	return &NullableOrderGetOrderRequest{value: val, isSet: true}
}

func (v NullableOrderGetOrderRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderGetOrderRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


