/*
order Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package order

import (
	"encoding/json"
)

// checks if the OrderCreateHistoryRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrderCreateHistoryRequest{}

// OrderCreateHistoryRequest struct for OrderCreateHistoryRequest
type OrderCreateHistoryRequest struct {
	TenantId *string `json:"tenantId,omitempty"`
	OrderId *string `json:"orderId,omitempty"`
	Comment *string `json:"comment,omitempty"`
}

// NewOrderCreateHistoryRequest instantiates a new OrderCreateHistoryRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrderCreateHistoryRequest() *OrderCreateHistoryRequest {
	this := OrderCreateHistoryRequest{}
	return &this
}

// NewOrderCreateHistoryRequestWithDefaults instantiates a new OrderCreateHistoryRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrderCreateHistoryRequestWithDefaults() *OrderCreateHistoryRequest {
	this := OrderCreateHistoryRequest{}
	return &this
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *OrderCreateHistoryRequest) GetTenantId() string {
	if o == nil || IsNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCreateHistoryRequest) GetTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *OrderCreateHistoryRequest) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *OrderCreateHistoryRequest) SetTenantId(v string) {
	o.TenantId = &v
}

// GetOrderId returns the OrderId field value if set, zero value otherwise.
func (o *OrderCreateHistoryRequest) GetOrderId() string {
	if o == nil || IsNil(o.OrderId) {
		var ret string
		return ret
	}
	return *o.OrderId
}

// GetOrderIdOk returns a tuple with the OrderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCreateHistoryRequest) GetOrderIdOk() (*string, bool) {
	if o == nil || IsNil(o.OrderId) {
		return nil, false
	}
	return o.OrderId, true
}

// HasOrderId returns a boolean if a field has been set.
func (o *OrderCreateHistoryRequest) HasOrderId() bool {
	if o != nil && !IsNil(o.OrderId) {
		return true
	}

	return false
}

// SetOrderId gets a reference to the given string and assigns it to the OrderId field.
func (o *OrderCreateHistoryRequest) SetOrderId(v string) {
	o.OrderId = &v
}

// GetComment returns the Comment field value if set, zero value otherwise.
func (o *OrderCreateHistoryRequest) GetComment() string {
	if o == nil || IsNil(o.Comment) {
		var ret string
		return ret
	}
	return *o.Comment
}

// GetCommentOk returns a tuple with the Comment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCreateHistoryRequest) GetCommentOk() (*string, bool) {
	if o == nil || IsNil(o.Comment) {
		return nil, false
	}
	return o.Comment, true
}

// HasComment returns a boolean if a field has been set.
func (o *OrderCreateHistoryRequest) HasComment() bool {
	if o != nil && !IsNil(o.Comment) {
		return true
	}

	return false
}

// SetComment gets a reference to the given string and assigns it to the Comment field.
func (o *OrderCreateHistoryRequest) SetComment(v string) {
	o.Comment = &v
}

func (o OrderCreateHistoryRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrderCreateHistoryRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TenantId) {
		toSerialize["tenantId"] = o.TenantId
	}
	if !IsNil(o.OrderId) {
		toSerialize["orderId"] = o.OrderId
	}
	if !IsNil(o.Comment) {
		toSerialize["comment"] = o.Comment
	}
	return toSerialize, nil
}

type NullableOrderCreateHistoryRequest struct {
	value *OrderCreateHistoryRequest
	isSet bool
}

func (v NullableOrderCreateHistoryRequest) Get() *OrderCreateHistoryRequest {
	return v.value
}

func (v *NullableOrderCreateHistoryRequest) Set(val *OrderCreateHistoryRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderCreateHistoryRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderCreateHistoryRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderCreateHistoryRequest(val *OrderCreateHistoryRequest) *NullableOrderCreateHistoryRequest {
	return &NullableOrderCreateHistoryRequest{value: val, isSet: true}
}

func (v NullableOrderCreateHistoryRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderCreateHistoryRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


