/*
order Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package order

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OrderCreateHistoryRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrderCreateHistoryRequest{}

// OrderCreateHistoryRequest struct for OrderCreateHistoryRequest
type OrderCreateHistoryRequest struct {
	TenantId string `json:"tenantId"`
	OrderId string `json:"orderId"`
	Comment *string `json:"comment,omitempty"`
}

type _OrderCreateHistoryRequest OrderCreateHistoryRequest

// NewOrderCreateHistoryRequest instantiates a new OrderCreateHistoryRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrderCreateHistoryRequest(tenantId string, orderId string) *OrderCreateHistoryRequest {
	this := OrderCreateHistoryRequest{}
	this.TenantId = tenantId
	this.OrderId = orderId
	return &this
}

// NewOrderCreateHistoryRequestWithDefaults instantiates a new OrderCreateHistoryRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrderCreateHistoryRequestWithDefaults() *OrderCreateHistoryRequest {
	this := OrderCreateHistoryRequest{}
	return &this
}

// GetTenantId returns the TenantId field value
func (o *OrderCreateHistoryRequest) GetTenantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *OrderCreateHistoryRequest) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *OrderCreateHistoryRequest) SetTenantId(v string) {
	o.TenantId = v
}

// GetOrderId returns the OrderId field value
func (o *OrderCreateHistoryRequest) GetOrderId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrderId
}

// GetOrderIdOk returns a tuple with the OrderId field value
// and a boolean to check if the value has been set.
func (o *OrderCreateHistoryRequest) GetOrderIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrderId, true
}

// SetOrderId sets field value
func (o *OrderCreateHistoryRequest) SetOrderId(v string) {
	o.OrderId = v
}

// GetComment returns the Comment field value if set, zero value otherwise.
func (o *OrderCreateHistoryRequest) GetComment() string {
	if o == nil || IsNil(o.Comment) {
		var ret string
		return ret
	}
	return *o.Comment
}

// GetCommentOk returns a tuple with the Comment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderCreateHistoryRequest) GetCommentOk() (*string, bool) {
	if o == nil || IsNil(o.Comment) {
		return nil, false
	}
	return o.Comment, true
}

// HasComment returns a boolean if a field has been set.
func (o *OrderCreateHistoryRequest) HasComment() bool {
	if o != nil && !IsNil(o.Comment) {
		return true
	}

	return false
}

// SetComment gets a reference to the given string and assigns it to the Comment field.
func (o *OrderCreateHistoryRequest) SetComment(v string) {
	o.Comment = &v
}

func (o OrderCreateHistoryRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrderCreateHistoryRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["tenantId"] = o.TenantId
	toSerialize["orderId"] = o.OrderId
	if !IsNil(o.Comment) {
		toSerialize["comment"] = o.Comment
	}
	return toSerialize, nil
}

func (o *OrderCreateHistoryRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tenantId",
		"orderId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOrderCreateHistoryRequest := _OrderCreateHistoryRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOrderCreateHistoryRequest)

	if err != nil {
		return err
	}

	*o = OrderCreateHistoryRequest(varOrderCreateHistoryRequest)

	return err
}

type NullableOrderCreateHistoryRequest struct {
	value *OrderCreateHistoryRequest
	isSet bool
}

func (v NullableOrderCreateHistoryRequest) Get() *OrderCreateHistoryRequest {
	return v.value
}

func (v *NullableOrderCreateHistoryRequest) Set(val *OrderCreateHistoryRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderCreateHistoryRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderCreateHistoryRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderCreateHistoryRequest(val *OrderCreateHistoryRequest) *NullableOrderCreateHistoryRequest {
	return &NullableOrderCreateHistoryRequest{value: val, isSet: true}
}

func (v NullableOrderCreateHistoryRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderCreateHistoryRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


